Upload pasted image on editor
rainlab/blog-plugin pull request #495
Opened 2020-03-28 13:06 UTC by marzochi

2020-03-29 14:31 UTC, bennothommo requested changes
@marzochi Some code cleanup required before we can review and potentially merge this.

2020-03-29 14:31 UTC, bennothommo commented on assets/js/post-form.js
> +                event.clipboardData = event.originalEvent.clipboardData;
@marzochi Our JS code style is no semicolons currently, so would you mind removing them from this line and any other line that contains them.
```suggestion
                event.clipboardData = event.originalEvent.clipboardData
```

2020-03-29 14:31 UTC, bennothommo commented on assets/js/post-form.js
> +            if (clipboardData.types.indexOf('Files') != -1) {
@marzochi 
```suggestion
            if (clipboardData.types.indexOf('Files') !== -1) {
```

2020-03-29 14:31 UTC, bennothommo commented on assets/js/post-form.js
> +                    jQuery.ajax({
@marzochi 
```suggestion
                    $.ajax({
```

2020-03-29 14:31 UTC, bennothommo commented on assets/js/post-form.js
> +                    .done(function(response) {
@marzochi 
```suggestion
                    .done(function (response) {
```

2020-03-29 14:31 UTC, bennothommo commented on assets/js/post-form.js
> +                    .fail(function(response) {
@marzochi 
```suggestion
                    .fail(function (response) {
```

2020-03-29 14:31 UTC, bennothommo commented on formwidgets/BlogMarkdown.php
> +                    $uploadedFileName = $uploadedFile->getClientOriginalName();
@marzochi We follow PSR-2 guidelines, so all conditions need surrounding braces.
```suggestion
                if ($uploadedFile) {
                    $uploadedFileName = $uploadedFile->getClientOriginalName();
                }
```

2020-03-29 14:31 UTC, bennothommo commented on formwidgets/BlogMarkdown.php
> +
@marzochi
```suggestion
            } elseif (Input::has('_image')) {
```

2020-03-29 14:31 UTC, bennothommo commented on formwidgets/BlogMarkdown.php
> +                $file_content = base64_decode( str_replace( $result[1], '', $content ) );
@marzochi 
```suggestion
                $fileContent = base64_decode(str_replace($result[1], '', $content));
```

2020-03-29 14:31 UTC, bennothommo commented on formwidgets/BlogMarkdown.php
> +                $file_ext = $result[2];
@marzochi 
```suggestion
                $fileExt = $result[2];
```

2020-03-29 14:31 UTC, bennothommo commented on formwidgets/BlogMarkdown.php
> +                $file_name = md5( $file_content ) . "." . $file_ext;
@marzochi 
```suggestion
                $fileName = md5($file_content) . '.' . $fileExt;
```

2020-03-29 14:31 UTC, bennothommo commented on formwidgets/BlogMarkdown.php
> +                $uploadedFileName = "image" . "." . $file_ext;
@marzochi 
```suggestion
                $uploadedFileName = 'image' . '.' . $fileExt;
```

2020-03-29 14:31 UTC, bennothommo commented on formwidgets/BlogMarkdown.php
> +                $file->fromData($file_content, $file_name);
@marzochi 
```suggestion
                $file->fromData($fileContent, $fileName);
```

2020-03-29 14:31 UTC, bennothommo commented on assets/js/post-form.js
> +                    formData.append("_image", evt.target.result)
@marzochi 
```suggestion
                    formData.append('_image', evt.target.result)
```

2020-03-29 14:31 UTC, bennothommo commented on assets/js/post-form.js
> +                        type: "POST",
@marzochi 
```suggestion
                        type: 'POST',
```

2020-03-29 14:38 UTC, mhanoglu reviewed
Thanks a lot

2020-03-29 14:43 UTC, bennothommo commented
@marzochi Thanks for making those changes - just make sure to do the following as well:
https://github.com/rainlab/blog-plugin/pull/495#discussion_r399804412

2020-03-29 15:20 UTC, marzochi commented
Thanks again, I removed unnecessary codes. I hope it'll be passed :)

2021-04-05 04:09 UTC, daftspunk commented
Very cool @mhanoglu. Added a note to review this and implement into the core widget

Thanks!

2026-04-03 03:37 UTC, closed without merging